version: '3.6'
services:
  kafka-broker-1:
    image: loraneo/docker-kafka-broker:2.0.0a
    networks:
      - dev
    environment:
      - BROKER_ID=1

      
  kafka-broker-2:
    image: loraneo/docker-kafka-broker:2.0.0a
    networks:
      - dev
    environment:
      - BROKER_ID=2
  kafka-broker-3:
    image: loraneo/docker-kafka-broker:2.0.0a
    networks:
      - dev
    environment:
      - BROKER_ID=3
  zookeper-1:
    image: loraneo/docker-zookeeper:3.4.10a
    networks:
      - dev
    environment:
      - MY_ID=1
    deploy:
      endpoint_mode: dnsrr
  zookeper-2:
    image: loraneo/docker-zookeeper:3.4.10a
    networks:
      - dev
    environment:
      - MY_ID=2
    deploy:
      endpoint_mode: dnsrr
  zookeper-3:
    image: loraneo/docker-zookeeper:3.4.10a
    networks:
      - dev  
    environment:
      - MY_ID=3
    deploy:
      endpoint_mode: dnsrr
  cdr-gen:
    image: loraneo/cdr-gen:1.0.0a
    networks:
      - dev
  cdr-kafka-stream:
    image: loraneo/cdr-kafka-stream:1.0.0a
    networks:
      - dev    
  kafka-connect:
    image: loraneo/docker-kafka-connect:2.0.0a
    networks:
      - dev
    ports:
      - 8083:8083   
networks:
  dev: