version: '3.6'
services:
  kafka-broker-1:
    image: loraneo/docker-kafka-broker:2.0.0a
    networks:
    - dev
    environment:
    - BROKER_ID=1
    volumes:
    - kafka-1:/var/lib/kafka-logs
    deploy:
      deploy:
        resources:
          limits:
            memory: 2048M
  kafka-broker-2:
    image: loraneo/docker-kafka-broker:2.0.0a
    networks:
    - dev
    environment:
    - BROKER_ID=2
    volumes:
    - kafka-2:/var/lib/kafka-logs
    deploy:
      resources:
        limits:
          memory: 2048M
  kafka-broker-3:
    image: loraneo/docker-kafka-broker:2.0.0a
    networks:
    - dev
    environment:
    - BROKER_ID=3
    volumes:
    - kafka-3:/var/lib/kafka-logs
    deploy:
      resources:
        limits:
          memory: 2048M
  zookeper-1:
    image: loraneo/docker-zookeeper:3.4.10a
    networks:
    - dev
    environment:
    - MY_ID=1
    deploy:
      resources:
        limits:
          memory: 2048M
    volumes:
    - zookeeper-1:/opt/zookeeper/data
  zookeper-2:
    image: loraneo/docker-zookeeper:3.4.10a
    networks:
    - dev
    environment:
    - MY_ID=2
    deploy:
      resources:
        limits:
          memory: 2048M
    volumes:
    - zookeeper-2:/opt/zookeeper/data
  zookeper-3:
    image: loraneo/docker-zookeeper:3.4.10a
    networks:
    - dev
    environment:
    - MY_ID=3
    deploy:
      resources:
        limits:
          memory: 2048M
    volumes:
    - zookeeper-3:/opt/zookeeper/data
  cdr-gen:
    image: loraneo/cdr-gen:1.0.0a
    networks:
    - dev
    deploy:
      resources:
        limits:
          memory: 512M
  cdr-kafka-stream:
    image: loraneo/cdr-kafka-stream:1.0.0a
    networks:
    - dev
    deploy:
      resources:
        limits:
          memory: 512M
  kafka-connect:
    image: loraneo/docker-kafka-connect:2.0.0a
    networks:
    - dev
    ports:
    - 8083:8083
    deploy:
      resources:
        limits:
          memory: 1024M
networks:
  dev:
    attachable: true
volumes:
  kafka-1: null
  kafka-2: null
  kafka-3: null
  zookeeper-1: null
  zookeeper-2: null
  zookeeper-3: null